apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: echo
    name: echo
    namespace: default
  spec:
    externalTrafficPolicy: Local
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: echo
    sessionAffinity: None
    type: LoadBalancer
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
