apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: echo
    name: echo-77523-worker2
    namespace: default
  spec:
    containers:
    - image: inanimate/echo-server
      imagePullPolicy: Always
      name: echo
      ports:
      - containerPort: 8080
        protocol: TCP
    nodeName: 77523-worker2
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: netshoot
    name: netshoot-77523-worker
    namespace: default
  spec:
    containers:
    - command:
      - sleep
      - "9999"
      image: nicolaka/netshoot
      imagePullPolicy: Always
      name: netshoot
    hostNetwork: true
    nodeName: 77523-worker
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: netshoot
    name: netshoot-77523-worker2
    namespace: default
  spec:
    containers:
    - command:
      - sleep
      - "9999"
      image: nicolaka/netshoot
      imagePullPolicy: Always
      name: netshoot
    hostNetwork: true
    nodeName: 77523-worker2
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: overlay
    name: overlay-77523-worker
    namespace: default
  spec:
    containers:
    - command:
      - sleep
      - "9999"
      image: nicolaka/netshoot
      imagePullPolicy: Always
      name: overlay
    nodeName: 77523-worker
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: overlay
    name: overlay-77523-worker2
    namespace: default
  spec:
    containers:
    - command:
      - sleep
      - "9999"
      image: nicolaka/netshoot
      imagePullPolicy: Always
      name: overlay
    nodeName: 77523-worker2
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: echo
    name: echo
    namespace: default
  spec:
    externalTrafficPolicy: Local
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      run: echo
    sessionAffinity: None
    type: LoadBalancer
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
apiVersion: v1
